# -*- coding: utf-8 -*-
"""mysql_script_completo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcHZbalAfMf3rgVF-QpHA083BqsjgJvW

# Instalação do conector
"""

!pip install mysql-connector-python

import mysql.connector

import mysql.connector

mydb = mysql.connector.connect(
  host="database-1.c21fjnvngsvf.us-east-1.rds.amazonaws.com",
  user="admin",
  password="Senai12345"
)

print(mydb)

"""# MySQL Create Database

"""

mydb = mysql.connector.connect(
  host="database-1.c21fjnvngsvf.us-east-1.rds.amazonaws.com",
  user="admin",
  password="Senai12345"
)
mycursor = mydb.cursor()
mycursor.execute("CREATE DATABASE IF NOT EXISTS mydatabase")

import mysql.connector

mydb = mysql.connector.connect(
  host="database-1.c21fjnvngsvf.us-east-1.rds.amazonaws.com",
  user="admin",
  password="Senai12345"
)

mycursor = mydb.cursor()

mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

"""# MySQL Create Table"""

mydb = mysql.connector.connect(
  host="database-1.c21fjnvngsvf.us-east-1.rds.amazonaws.com",
  user="admin",
  password="Senai12345",
  database="mydatabase"
)
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE customers (name VARCHAR(255), address VARCHAR(255))")

import mysql.connector

mydb = mysql.connector.connect(
  host="database-1.c21fjnvngsvf.us-east-1.rds.amazonaws.com",
  user="admin",
  password="Senai12345",
  database="mydatabase"
)

mycursor = mydb.cursor()

mycursor.execute("SHOW TABLES")

for x in mycursor:
  print(x)

"""# MySQL Insert"""

import mysql.connector

mydb = mysql.connector.connect(
  host="database-1.c21fjnvngsvf.us-east-1.rds.amazonaws.com",
  user="admin",
  password="Senai12345",
  database="mydatabase"
)

mycursor = mydb.cursor()

sql = "INSERT INTO customers (name, address) VALUES (%s, %s)"
val = [
  ("Ana", "Rua das Flores 123"),
  ("Carlos", "Av. Brasil 456"),
  ("Mariana", "Rua do Sol 789"),
  ("Pedro", "Travessa das Palmeiras 101"),
  ("Juliana", "Av. Central 202")
]

mycursor.executemany(sql, val)

mydb.commit()

print(mycursor.rowcount, "records inserted.")

"""# MySQL Select"""

mycursor.execute("SELECT * FROM customers")
myresult = mycursor.fetchone()
print(myresult)

"""# MySQL Where"""

sql = "SELECT * FROM customers WHERE address = 'Rua das Flores 123'"
mycursor.execute(sql)
myresult = mycursor.fetchall()
for x in myresult:
  print(x)

"""# MySQL Order By"""

sql = "SELECT * FROM customers ORDER BY name"
mycursor.execute(sql)
myresult = mycursor.fetchall()
for x in myresult:
  print(x)

"""# MySQL Update"""

sql = "UPDATE customers SET address = 'Canyon 123' WHERE address = 'Rua das Flores 123'"
mycursor.execute(sql)
mydb.commit()

"""# MySQL Delete"""

sql = "DELETE FROM customers WHERE address = 'Av. Central 202'"
mycursor.execute(sql)
mydb.commit()

"""# MySQL Limit"""

mycursor.execute("SELECT * FROM customers LIMIT 5")
myresult = mycursor.fetchall()
for x in myresult:
  print(x)

"""# MySQL Join"""

sql = '''
  SELECT
    customers.name AS user,
    customers.address AS favorite_address
  FROM customers
'''
mycursor.execute(sql)
myresult = mycursor.fetchall()
for x in myresult:
  print(x)